name: ais3uson_app
description: A Flutter backend for AIS-3USON

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.2+28

environment:
  sdk: ">=3.0.0"


dependencies:
  app_bar_with_search_switch: ^2.0.0-dev.14
  audioplayers: any
  camera: any
  collection: any
  context_menus: any
  dartdoc: ^6.3.0
  flutter:
    sdk: flutter
  flutter_hooks: any
  flutter_html: any
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation: any
  get_it: any
  go_router:
  google_fonts: any
  hive:
  hive_flutter: any
  http: any
  intl: any
  #  itertools: any
  #  intl_utils: any
  json_annotation: any
  lint: any
  locale_switcher:
#    path: ../locale_switcher/
  logging: any
  mockito: any
  overlay_support: any
  path: any
  path_provider: any
  peanut: any
  provider: any
  qr_code_scanner: any
  quiver: any
  record: ^5.0.0-beta.2
  riverpod: any
  riverpod_annotation: any
  share_plus: any
  shared_preferences: any
  speech_to_text: any
  synchronized: any
  toggle_switch: any
  tuple: any
  universal_html: any
  uuid: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: any
dependency_overrides:
  hive: "^3.0.0-dev"

dev_dependencies:
  #  analyzer: ^4.2.0
  #  analyzer_plugin: 0.11.0
  build_runner: any
  custom_lint:
  dart_code_metrics: ^5.7.0
  flutter_launcher_icons: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed:
  hive_generator: ^2.0.1
  #  hive_test: any
  #  http_certificate_pinning: any
  integration_test:
    sdk: flutter
  json_serializable:
  lints:
#  locale_switcher_dev:
  path_provider_platform_interface: any
  plugin_platform_interface: any
  riverpod_generator: any
  riverpod_lint:
  surf_lint_rules: any

#  very_good_analysis: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/ais-3uson-logo.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - images/
    - assets/
    - assets/ca/lets-encrypt-r3.pem
