// ignore_for_file: non_constant_identifier_names

import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'client_entry.freezed.dart';

part 'client_entry.g.dart';

/// Immutable class to create [ClientEntry] from JSON strings.
///
/// Autogenerated from test data like this:
/// ```
/// api_key : "123"
/// contract_id : 1
/// dep_id : 1
/// client_id : 1
/// contract : "12312313/2001"
/// client : "Тес. *. ч-ек"
/// dhw_id : 1
/// ```
/// {@category Client-Server API}
@freezed
class ClientEntry with _$ClientEntry {
  const factory ClientEntry({
    required int contract_id,
    required int dep_id,
    required int client_id,
    required int dhw_id,
    @Default('ERROR') String contract,
    @Default('ERROR') String client,
    @Default('') String contract_duration,
    @Default('') String comment,
    @Default(0.0) double percent,
    @Default(double.infinity) double max_pay,
  }) = _ClientEntry;

  const ClientEntry._();

  factory ClientEntry.fromJson(Map<String, dynamic> json) =>
      _$$_ClientEntryFromJson(json);

  int get contractId => contract_id;

  int get depId => dep_id;

  int get clientId => client_id;

  int get dhwId => dhw_id;

  String get contractDuration => contract_duration;

  double get maxPay => max_pay;
}
