import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'client_entry.freezed.dart';

part 'client_entry.g.dart';

/// Immutable class to create [ClientEntry] from JSON strings.
///
/// Autogenerated from test data like this:
/// api_key : "123"
/// contract_id : 1
/// dep_id : 1
/// client_id : 1
/// contract : "12312313/2001"
/// client : "Тес. *. ч-ек"
/// dhw_id : 1
///
/// {@category Import_from_json}
@freezed
class ClientEntry with _$ClientEntry {
  int get contractId => contract_id;

  int get depId => dep_id;

  int get clientId => client_id;

  int get dhwId => dhw_id;

  const factory ClientEntry({
    required int contract_id,
    required int dep_id,
    required int client_id,
    @Default('ERROR') String contract,
    @Default('ERROR') String client,
    required int dhw_id,
  }) = _ClientEntry;

  const ClientEntry._();

  factory ClientEntry.fromJson(Map<String, dynamic> json) =>
      _$$_ClientEntryFromJson(json);
}
