// ignore_for_file: non_constant_identifier_names

import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'client_plan.freezed.dart';

part 'client_plan.g.dart';

/// Immutable class to create [ClientPlan] from/to JSON strings.
///
/// Autogenerated from test data like this:
/// contract_id : 2
/// serv_id : 1
/// planned : 10
/// filled : 5
///
/// {@category Import_from_json}
@freezed
class ClientPlan with _$ClientPlan {
  int get contractId => contract_id;

  int get servId => serv_id;

  const factory ClientPlan({
    required int contract_id,
    required int serv_id,
    required int planned,
    required int filled,
  }) = _ClientPlan;

  const ClientPlan._();

  factory ClientPlan.fromJson(Map<String, dynamic> json) =>
      _$$_ClientPlanFromJson(json);
}
