// import 'package:flutter/material.dart';
// ignore_for_file:invalid_assignment
// ignore_for_file:avoid_dynamic_calls

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/material.dart';

/// Autogenerated from test data like this:
/// app : "AIS3USON web"
/// api_key : "3.015679841875732e17ef73dc17-7af8-11ec-b7f8-04d9f5c97b0c"
/// name : "Test"
/// worker_dep_id: 1
/// dep_id : 1
/// dep : "Test Department"
/// host : "192.168.0.102"
/// port : "48080"
/// db : "kcson"
/// comment : "any text"
/// certBase64 : ""
///
/// {@category Import_from_json}
@immutable
class WorkerKey {
  late final String _app;
  late final String _name;
  late final String _apiKey;
  late final int _workerDepId;
  late final String _dep;
  late final String _db;
  late final String _host;
  late final String _port;
  late final String _certBase64;
  late final String _comment;

  String get app => _app;

  String get name => _name;

  String get apiKey => _apiKey;

  int get workerDepId => _workerDepId;

  String get dep => _dep;

  String get db => _db;

  String get host => _host;

  String get port => _port;

  String get httpBody => '''{"api_key": $_apiKey}''';

  String get comment => _comment;

  Uint8List get certificate => const Base64Decoder().convert(_certBase64);

  @override
  int get hashCode {
    return '${_apiKey.hashCode} + ${_dep.hashCode} + ${_host.hashCode}'
        .hashCode;
  }

  WorkerKey({
    required String app,
    required String name,
    required String apiKey,
    required int workerDepId,
    required String dep,
    required String db,
    required String host,
    required String port,
    String? comment,
    String? certBase64,
  }) {
    _app = app;
    _name = name;
    _apiKey = apiKey;
    _workerDepId = workerDepId;
    _dep = dep;
    _db = db;
    _host = host;
    _port = port;
    _comment = comment ?? '';
    _certBase64 = certBase64 ?? '';
  }

  // ignore: avoid_annotating_with_dynamic
  WorkerKey.fromJson(Map<String, dynamic> json) {
    _app = json['app'];
    _name = json['name'];
    _apiKey = json['api_key'];
    _workerDepId = json['worker_dep_id'];
    _dep = json['dep'];
    _db = json['db'];
    _host = json['host'];
    _port = json['port'];
    _comment = json.containsKey('comment') ? json['comment'] : '';
    _certBase64 = json.containsKey('certBase64') ? json['certBase64'] : '';
  }

  @override
  // ignore: avoid_annotating_with_dynamic
  bool operator ==(dynamic other) {
    if (other.runtimeType != WorkerKey) {
      return false;
    }

    // other = other as WorkerKey;
    return _app == other.app &&
        _name == other.name &&
        _apiKey == other.apiKey &&
        _workerDepId == other.workerDepId &&
        _dep == other.dep &&
        _db == other.db &&
        _host == other.host &&
        _comment == other.comment &&
        _port == other.port;
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['app'] = _app;
    map['name'] = _name;
    map['api_key'] = _apiKey;
    map['worker_dep_id'] = _workerDepId;
    map['dep'] = _dep;
    map['db'] = _db;
    map['host'] = _host;
    map['port'] = _port;
    map['certBase64'] = _certBase64;
    map['comment'] = _comment;

    return map;
  }
}
