// ignore_for_file: non_constant_identifier_names
import 'package:freezed_annotation/freezed_annotation.dart';

part 'service_entry.freezed.dart';

part 'service_entry.g.dart';

/// Autogenerated from test data like this:
/// id : 558
/// tnum : ""
/// serv_text : ":"
/// total : 1
/// image : "None"
/// serv_id_list : "558807"
///
/// {@category Client-Server API}

@freezed
class ServiceEntry with _$ServiceEntry {
  const factory ServiceEntry({
    required int id,
    required String serv_text,
    @Default('not-found.png') String image,
    @Default('___') String tnum,
    @Default(0) int total,
    @Default('') String short_text,
    @Default('') String serv_id_list,
    @Default(1) int sub_serv, // subServiceOf
    @Default('') String comment,
    @Default(0.0) double price,
  }) = _ServiceEntry;

  const ServiceEntry._();

  factory ServiceEntry.fromJson(Map<String, dynamic> json) =>
      _$$_ServiceEntryFromJson(json);

  String get imagePath {
    if (total != 0) {
      return image != 'not-found.png' ? image : 'total.png';
    }

    return image;
  }

  String get servTextAdd {
    if (short_text.isEmpty || serv_text.startsWith(short_text)) {
      final res = serv_text.substring(shortText.length, serv_text.length);

      return res.isNotEmpty ? '...$res' : '';
    }

    return serv_text;
  }

  String get shortText {
    if (short_text.isNotEmpty) return short_text;
    final shText = serv_text.substring(
      0,
      100 > serv_text.length ? serv_text.length : 100,
    );

    return shText;
  }

  String get tNum => tnum;

  String get servText => serv_text;

  String get servIdList => serv_id_list;

  int get subServ => sub_serv;
}
