# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Add dartdoc
        run: dart pub add dartdoc
      - name: Install dependencies
        run: dart pub get


      - name: Generate docs
        run: ./regenerate_documentation.sh


      - uses: actions-go/push@master
        with:
          create-commit: true
          commit-message: '[Auto] documentation update'
          remote: origin
          fail-if-empty: true
