# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Generate documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: 2.14
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter
     
      - name: Add dartdoc
        run: dart pub add dartdoc
      - name: Install dependencies
        run: flutter pub get

      - name: Generate docs
        run: ./regenerate_documentation.sh

      # - name: Uplad docs
      - uses: actions-go/push@master
        with:
          create-commit: true
          commit-message: '[Auto] documentation update'
          remote: origin
          fail-if-empty: true
