# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test+Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          # flutter-version: 2.14
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter
          
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test --coverage 
        
      - name: Upload coverage to Codecov
        # uses: actions/checkout@master
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          # flags: unittests # optional
          directory: ./coverage/
          # version: "v0.1.15"
          verbose: true # optional (default = false)
          # name: codecov # optional
          # files: lcov.info
          # fail_ci_if_error: true # optional (default = false)
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          
        
      - name: Build web3uson
        run: flutter build web --release
        
      - name: Move web to docs
        run: |
          mv 'build/web/' 'build/docs/'
          
      - name: Deploy ais3uson to web
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.WEB3USON }}
        with:
          source_file: 'build/docs/'
          destination_repo: 'Alexqwesa/web3uson'
          # destination_folder: 'docs/'
          user_email: 'alexo.veto@gmail.com'
          user_name: 'Alexqwesa'
          commit_message: 'Deploy ais3uson to web'
